// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjbcxjxveksuuvlosmsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqYmN4anh2ZWtzdXV2bG9zbXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzM5NzYsImV4cCI6MjA3MTEwOTk3Nn0.rkoDQ7kc_RfAHShSxe3sX8QCqCxteBxUzSGoWbfgC30";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});